<html>
    <head>
        <meta charset="utf-8">
        <title>TGS</title>
        <meta name="viewport" content="width=device-width, user-scalable=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">TGS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Login</a>
                    </li>
                    <li class="nav-item float-right">
                        <a class="nav-link" href="#">Criar usuário</a>
                    </li>
                </ul>
            </div>
        </nav>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Item</th>
                    <th scope="col">Dono</th>
                    <th scope="col">Local onde encontrou</th>
                    <th scope="col">Com quem está</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">RG</th>
                    <td>Mauricio Ernandes da Silva</td>
                    <td>Banheiro do CTC</td>
                    <td><a href="/@mermando_soares">@mermando_soares</a></td>
                </tr>
                <tr>
                    <th scope="row">Celular</th>
                    <td>Jacob</td>
                    <td>Um dos bancos na frente do CCE</td>
                    <td><a href="/@fabio_gonsalves">@fabio_gonsalves</a></td>
                </tr>
                <tr>
                    <th scope="row">mochila</th>
                    <td>Larry</td>
                    <td>BU</td>
                    <td><a href="/@Larry">@Larry</a></td>
                </tr>
            </tbody>
        </table>
        
        <!-- Scripts -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>